(gmode 512 512)
(defun points (j)
       (gmode t)
       (cls)
       (dotimes (i 15)
                (colors (1+ i))
                (dotimes (k j)
                         (point (random 512) (random 512)))
                (gmode t))
       (gmode nil))
